const devices=[
 {name:'Finalmouse ULX Frostlord',type:'MOUSE',desc:'PRIMARY GAMING MOUSE',url:'https://finalmouse.com/products/ulx-frostlord',img:'assets/mouse.svg'},
 {name:'Wooting 60HE v2',type:'KEYBOARD',desc:'60% / RAPID TRIGGER',url:'https://wooting.io/ja/wooting-60he-v2',img:'assets/keyboard.svg'},
 {name:'Summer Miku',type:'MOUSE PAD',desc:'WALLHACK / SP-004',url:'https://wallhack.com/ja-jp/pages/campaigns/summer-miku',img:'assets/pad.svg'},
 {name:'Twin Pad',type:'MOUSE PAD',desc:'WALLHACK / LIMITED',url:'https://wallhack.com/ja-jp/pages/campaigns/twin-pad',img:'assets/twin.svg'},
 {name:'PRO Sleeve',type:'ARM SLEEVE',desc:'WALLHACK / PRO SERIES',url:'https://wallhack.com/ja-jp/products/pro-sleeve',img:'assets/sleeve.svg'},
 {name:'Skates Dots',type:'MOUSE SKATES',desc:'WALLHACK / UHMW-PE',url:'https://wallhack.com/ja-jp/products/skates-dots',img:'assets/skates.svg'}
];
const carousel=document.querySelector('#carousel');const total=document.querySelector('#total');total.textContent=String(devices.length).padStart(2,'0');
devices.forEach((d,i)=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="card-art"><img src="${d.img}" alt="${d.name}"></div><div class="card-info"><div class="card-no">${String(i+1).padStart(2,'0')} / ${d.type}</div><h3>${d.name}</h3><p>${d.desc}</p><a class="product" href="${d.url}" target="_blank" rel="noopener">VIEW PRODUCT <span>↗</span></a></div>`;carousel.appendChild(el)});
const cards=[...document.querySelectorAll('.card')],current=document.querySelector('#current'),progress=document.querySelector('#progress');
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){cards.forEach(c=>c.classList.remove('active'));e.target.classList.add('active');const i=cards.indexOf(e.target)+1;current.textContent=String(i).padStart(2,'0');progress.style.width=(i/devices.length*100)+'%'}}),{root:carousel,threshold:.62});cards.forEach(c=>io.observe(c));cards[0].classList.add('active');
function move(dir){const active=document.querySelector('.card.active')||cards[0];const i=cards.indexOf(active);const n=Math.max(0,Math.min(cards.length-1,i+dir));cards[n].scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}document.querySelector('#prev').onclick=()=>move(-1);document.querySelector('#next').onclick=()=>move(1);
let dragging=false,startX=0,startScroll=0;carousel.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;startScroll=carousel.scrollLeft;carousel.classList.add('dragging');carousel.setPointerCapture(e.pointerId)});carousel.addEventListener('pointermove',e=>{if(dragging)carousel.scrollLeft=startScroll-(e.clientX-startX)*1.15});carousel.addEventListener('pointerup',()=>{dragging=false;carousel.classList.remove('dragging')});carousel.addEventListener('pointercancel',()=>{dragging=false;carousel.classList.remove('dragging')});
window.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
const cursor=document.querySelector('#cursor');window.addEventListener('pointermove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'});document.querySelectorAll('a,button').forEach(x=>{x.addEventListener('mouseenter',()=>{cursor.style.width='34px';cursor.style.height='34px'});x.addEventListener('mouseleave',()=>{cursor.style.width='14px';cursor.style.height='14px'})});
const menu=document.querySelector('#menu'),panel=document.querySelector('#menuPanel');menu?.addEventListener('click',()=>panel.classList.toggle('open'));panel?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>panel.classList.remove('open')));
setTimeout(()=>document.querySelector('#loader').classList.add('hide'),1450);document.querySelector('#loader').addEventListener('transitionend',e=>{if(e.propertyName==='opacity')e.currentTarget.remove()});
const style=document.createElement('style');style.textContent='.loader{transition:opacity .45s}.loader.hide{opacity:0;pointer-events:none}';document.head.appendChild(style);
